# Chemistry Domain Conflict Resolution Configuration
# -------------------------------------------------
# This YAML file defines how to resolve conflicts when multiple sources provide different values for the same attribute.
# Each attribute has its own conflict resolution strategy.
# Strategies can include: highest-priority source, highest confidence, human review, or custom logic.
# The reconciliation script will validate that all required strategies are defined for each entity.

Compound:
  name:
    strategy: "highest_priority"
    fallback: "first_source"
  formula:
    strategy: "highest_priority"
    fallback: "first_source"
  structure:
    strategy: "highest_priority"
    fallback: "first_source"
  molecular_mass_value:
    strategy: "average"
    fallback: "highest_priority"
  molecular_mass_unit:
    strategy: "most_common"
    fallback: "SI_default"
  melting_point_value:
    strategy: "average"
    fallback: "highest_priority"
  melting_point_unit:
    strategy: "most_common"
    fallback: "SI_default"
  boiling_point_value:
    strategy: "average"
    fallback: "highest_priority"
  boiling_point_unit:
    strategy: "most_common"
    fallback: "SI_default"
  density_value:
    strategy: "average"
    fallback: "highest_priority"
  density_unit:
    strategy: "most_common"
    fallback: "SI_default"
  length_value:
    strategy: "average"
    fallback: "highest_priority"
  length_unit:
    strategy: "most_common"
    fallback: "SI_default"
  acceleration_value:
    strategy: "average"
    fallback: "highest_priority"
  acceleration_unit:
    strategy: "most_common"
    fallback: "SI_default"

Reaction:
  name:
    strategy: "highest_priority"
    fallback: "first_source"
  reactants:
    strategy: "highest_priority"
    fallback: "first_source"
  products:
    strategy: "highest_priority"
    fallback: "first_source"
  conditions:
    strategy: "highest_priority"
    fallback: "first_source"
  yield:
    strategy: "average"
    fallback: "highest_priority"
  mechanism:
    strategy: "highest_priority"
    fallback: "first_source"
  reaction_type:
    strategy: "highest_priority"
    fallback: "first_source"

Catalyst:
  name:
    strategy: "highest_priority"
    fallback: "first_source"
  chemical_formula:
    strategy: "highest_priority"
    fallback: "first_source"
  catalyst_type:
    strategy: "highest_priority"
    fallback: "first_source"
  efficiency:
    strategy: "average"
    fallback: "highest_priority"
  reactions_catalyzed:
    strategy: "highest_priority"
    fallback: "first_source"

Solvent:
  name:
    strategy: "highest_priority"
    fallback: "first_source"
  chemical_formula:
    strategy: "highest_priority"
    fallback: "first_source"
  boiling_point:
    strategy: "average"
    fallback: "highest_priority"
  polarity:
    strategy: "highest_priority"
    fallback: "first_source"
  miscibility:
    strategy: "highest_priority"
    fallback: "first_source"

# End of chemistry conflict_resolution.yaml 