# =============================================================================
# SUBTYPE-LEVEL CONFLICT HANDLING (EXAMPLE)
# =============================================================================
# You can specify conflict resolution strategies for subtypes if needed:
#
# conflict_resolution:
#   Polymer:
#     monomer_units:
#       strategy: "union"
#       allow_human_review: true
#       notes: "Union of all unique monomer units for polymers."
# =============================================================================
conflict_resolution:
  Compound:
    name:
      strategy: "source_priority"
      allow_human_review: true
      notes: "Default for string attributes"
    formula:
      strategy: "source_priority"
      allow_human_review: true
      notes: "Default for formula attributes"
    molecular_mass_value:
      strategy: "average_if_numeric"
      allow_human_review: true
      notes: "Average numeric values if close, else escalate"
    molecular_mass_unit:
      strategy: "source_priority"
      allow_human_review: true
      notes: "Use unit from highest-priority source"
  Polymer:
    monomer_units:
      strategy: "union"
      allow_human_review: true
      notes: "Union of all unique monomer units for polymers." 