# =============================================================================
# ONTOLOGY REFERENCE
# =============================================================================
# This config aligns with ontology.yaml, which defines the entity type hierarchy (taxonomy),
# subdomains, tags, and relationships. Use subclass_of, subtypes, and tags as needed.
#
# Each attribute, when extracted, will include runtime feedback fields:
#   - value
#   - confidence (float, 0-1)
#   - source (string)
#   - version (string)
#   - provenance (dict)
# =============================================================================
chemistry:
  version: "1.1.0"
  domain: chemistry
  types:
    - name: Compound
      description: "Chemical compounds and molecules"
      subtypes: [OrganicCompound, Polymer, MetalComplex]
      tags: [core, chemical]
      subdomain: null
      attributes:
        - name: name
          type: string
          required: true
          validation: "string_validation"
          provenance: {}
        - name: formula
          type: string
          required: true
          validation: "chemical_formula_validation"
          provenance: {}
        - name: molecular_mass_value
          type: float
          required: false
          validation: "numeric_validation"
          provenance: {}
        - name: molecular_mass_unit
          type: string
          required: false
          validation: "unit_validation"
          provenance: {}
        # ... other attributes ...
    - name: OrganicCompound
      subclass_of: Compound
      tags: [organic]
      subdomain: organic
      description: "Organic chemical compounds"
      attributes:
        - name: functional_groups
          type: list
          required: false
          validation: "list_validation"
          provenance: {}
    - name: Polymer
      subclass_of: Compound
      tags: [polymer, macromolecule]
      subdomain: organic
      description: "Polymeric chemical compounds"
      attributes:
        - name: monomer_units
          type: list
          required: false
          validation: "list_validation"
          provenance: {}
    - name: MetalComplex
      subclass_of: Compound
      tags: [inorganic, metal]
      subdomain: inorganic
      description: "Metal complexes"
      attributes:
        - name: central_metal
          type: string
          required: true
          validation: "string_validation"
          provenance: {}
    - name: Reaction
      tags: [process]
      subdomain: null
      description: "Chemical reactions"
      attributes:
        - name: name
          type: string
          required: true
          validation: "string_validation"
          provenance: {}
        - name: reactants
          type: list
          required: true
          validation: "list_validation"
          provenance: {}
        - name: products
          type: list
          required: true
          validation: "list_validation"
          provenance: {}
        - name: conditions
          type: object
          required: false
          validation: "object_validation"
          provenance: {}
        - name: yield
          type: float
          required: false
          validation: "percentage_validation"
          provenance: {}
        - name: mechanism
          type: string
          required: false
          validation: "string_validation"
          provenance: {}
        - name: reaction_type
          type: string
          required: false
          validation: "enum_validation"
          provenance: {}
    - name: Catalyst
      tags: [catalyst]
      subdomain: null
      description: "Chemical catalysts"
      attributes:
        - name: name
          type: string
          required: true
          validation: "string_validation"
          provenance: {}
        - name: chemical_formula
          type: string
          required: true
          validation: "chemical_formula_validation"
          provenance: {}
        - name: catalyst_type
          type: string
          required: false
          validation: "enum_validation"
          provenance: {}
        - name: efficiency
          type: float
          required: false
          validation: "percentage_validation"
          provenance: {}
        - name: reactions_catalyzed
          type: list
          required: false
          validation: "list_validation"
          provenance: {} 