# =============================================================
# GENERIC EXTRACTION CONFIG TEMPLATE (DOMAIN-AGNOSTIC)
# =============================================================
# This file defines all extraction sources for ANY domain. It should NOT specify
# ontology entities or attributes. Mapping of entities/attributes to sources is
# handled in the source mapping config. This file is for source definitions only.
#
# IMPORTANT:
# - Do NOT specify the number of items to extract per source/strategy here.
# - Instead, set 'max_results' for each mapping in source_mapping.template.yaml.
#
# Each source can be:
#   - An API (e.g., PubChem, NCBI, UniProt, etc.)
#   - A database (e.g., SQL, NoSQL, proprietary)
#   - A file (e.g., CSV, Excel, JSON, etc.)
#   - Any other data provider
#
# Each source should have:
#   - name: Unique name for the source
#   - type: Must match the registered type in the source factory (e.g., api, csv, sql, etc.)
#   - enabled: true/false
#   - description: Short description of the source
#   - connection: All connection details needed by the source class (API URL, DB host, file path, etc.)
#
# Example (generic, for any domain):
# -----------------------------------------------------------------------------
# domain: <your_domain_name_here>
# version: "1.0.0"
# extraction_sources:
#   - name: example_api
#     type: api
#     enabled: true
#     description: "Example REST API for domain entities."
#     connection:
#       base_url: "https://api.example.com/v1"
#       timeout: 30
#       retries: 3
#       api_key: null  # If required, otherwise null
#       auth_type: none  # none|api_key|oauth2|basic
#   - name: local_csv
#     type: csv
#     enabled: false
#     description: "Local CSV file with entity data."
#     connection:
#       path: "./data/entities.csv"
#       delimiter: ","
#       encoding: "utf-8"
# extraction_parameters:
#   min_confidence: 0.75
#   # Note: To target specific categories in an external source, add a 'search_term' field to the entity type in entity_config.yaml.
#   #       The orchestrator will use this for category-based or keyword-based search if supported by the source.
#   enable_feature_x: true  # Example feature flag
#   enable_feature_y: true
#   provenance_tracking: true
#   record_all_occurrences: true
# -----------------------------------------------------------------------------
# END GENERIC EXAMPLE
# =============================================================
# =============================================================================
# CHEMISTRY DOMAIN EXAMPLE (Retain below)
# =============================================================================
domain: chemistry
version: "1.0.0"

# List all extraction sources for this domain. Each source should have:
# - name: Unique name for the source
# - type: Source type (must match the registered type in the source factory, e.g., pubchem, csv, sql, etc.)
# - enabled: true/false (whether to use this source)
# - description: Short description of the source
# - connection: Connection details (API URL, DB credentials, file path, etc.)
# - schema: Endpoints/tables/fields and their types
extraction_sources:
  - name: pubchem
    type: pubchem
    enabled: true
    description: "NCBI PubChem REST API for chemical compounds and properties."
    connection:
      base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
      timeout: 30
      retries: 3
      api_key: null  # If required, otherwise null
      auth_type: none  # none|api_key|oauth2|basic
  - name: rdkit
    type: rdkit
    enabled: true
    description: "RDKit for local cheminformatics (SMILES parsing, structure validation, property calculation)."
    connection:
      library: "rdkit"
      version: "2024.03.1"
  - name: reaxys
    type: reaxys
    enabled: false  # Set to true if available
    description: "Reaxys proprietary chemistry database."
    connection:
      host: "reaxys-db-host"
      port: 5432
      username: "user"
      password: "password"
      database: "reaxys"
      timeout: 30
      retries: 3
  - name: chebi
    type: chebi
    enabled: false
    description: "ChEBI (Chemical Entities of Biological Interest) API."
    connection:
      base_url: "https://www.ebi.ac.uk/chebi/ws"
      timeout: 30
      retries: 3
      api_key: null
      auth_type: none
  - name: local_csv
    type: csv
    enabled: false
    description: "Local CSV file with compound data."
    connection:
      path: "./data/compounds.csv"
      delimiter: ","
      encoding: "utf-8"

# Extraction parameters (optional, can be used by orchestrator)
extraction_parameters:
  min_confidence: 0.75
  # Note: To target specific categories in an external source, add a 'search_term' field to the entity type in entity_config.yaml.
  #       The orchestrator will use this for category-based or keyword-based search if supported by the source.
  enable_smiles_parsing: true
  enable_structure_parsing: true
  enable_relationship_extraction: true
  enable_metadata_extraction: true
  provenance_tracking: true
  record_all_occurrences: true

# =========================
# END OF TEMPLATE
# ========================= 