chemistry:
  version: "1.1.0"
  domain: chemistry
  types:
    - name: Polymer
      subclass_of: Compound
      tags: [polymer, macromolecule]
      subdomain: organic
      description: "Polymeric chemical compounds"
      attributes:
        - name: name
          type: string
          required: true
          validation: "string_validation"
          provenance: {}
        - name: monomer_units
          type: list
          required: false
          validation: "list_validation"
          provenance: {}
        - name: average_molecular_weight
          type: float
          required: false
          validation: "float_validation"
          provenance: {}
        - name: smiles
          type: string
          required: false
          validation: "string_validation"
          provenance: {}
        - name: molecular_weight
          type: float
          required: false
          validation: "float_validation"
          provenance: {}
        - name: synonyms
          type: list
          required: false
          validation: "list_validation"
          provenance: {}
        - name: formula
          type: string
          required: false
          validation: "chemical_formula_validation"
          provenance: {}
        - name: iupac_name
          type: string
          required: false
          validation: "string_validation"
          provenance: {}
      enrichment_rules:
        - name: pubchem_lookup
          input_fields: [name]
          api_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{name}/property/..."
          mapping_function: "pubchem_to_polymer"
          output_fields: [average_molecular_weight]
          source: "pubchem_api"
          enabled: true
          priority: 1
        - name: rdkit_smiles
          input_fields: [smiles]
          mapping_function: "rdkit_to_polymer"
          output_fields: [smiles]
          source: "rdkit"
          enabled: true
          priority: 2
      search_term: "polymer" 