# Extraction config for chemistry domain (test_config1)
domain: chemistry
version: "1.0.0"

extraction_sources:
    - name: pubchem
    type: pubchem
    enabled: true
    description: "NCBI PubChem REST API for chemical compounds and properties."
    connection:
        base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
        timeout: 30
      retries: 3
      api_key: null
      auth_type: none
    # schema is OPTIONAL and for documentation only. Remove if not needed.
    schema:
      compound:
        id_field: "CID"
        fields:
          - name: "IUPACName"
            type: string
          - name: "MolecularFormula"
            type: string
          - name: "MolecularWeight"
            type: float
    - name: rdkit
    type: rdkit
    enabled: true
    description: "RDKit for local cheminformatics (SMILES parsing, structure validation, property calculation)."
    connection:
        library: "rdkit"
        version: "2024.03.1"
    # schema is OPTIONAL and for documentation only. Remove if not needed.
    schema:
      compound:
        id_field: "smiles"
        fields:
          - name: "canonical_smiles"
            type: string
          - name: "molecular_weight"
            type: float

  extraction_parameters:
    min_confidence: 0.75
  max_entities_per_type:
    Polymer: 20
    enable_smiles_parsing: true
    enable_structure_parsing: true
    enable_relationship_extraction: true
    enable_metadata_extraction: true
    provenance_tracking: true
    record_all_occurrences: true 