Polymer:
  name:
    - source: pubchem
      endpoint: compound
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  monomer_units:
    - source: pubchem
      endpoint: compound
      priority: 1
      enabled: false
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  average_molecular_weight:
    - source: pubchem
      endpoint: property
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  smiles:
    - source: pubchem
      endpoint: property
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  molecular_weight:
    - source: pubchem
      endpoint: property
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  synonyms:
    - source: pubchem
      endpoint: synonyms
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  formula:
    - source: pubchem
      endpoint: property
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3
  iupac_name:
    - source: pubchem
      endpoint: property
      priority: 1
      enabled: true
      parameters: {}
      fallback: false
      timeout: 30
      retries: 3 